apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: &app otel-collector
spec:
  selector:
    matchLabels:
      app: *app
  maxUnavailable: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: &app otel-collector
  annotations:
    "app.uw.systems/description": "OpenTelemetry collector"
    "app.uw.systems/tier": "tier_3"
    "app.uw.systems/tags.oss": "true"
    "app.uw.systems/repos.manifests": "https://github.com/utilitywarehouse/opentelemetry-manifests"
spec:
  selector:
    matchLabels:
      app: *app
  minReadySeconds: 5
  progressDeadlineSeconds: 120
  template:
    metadata:
      name: *app
      labels:
        app: *app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8888"
        prometheus.io/path: /metrics
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: *app
          image: otel/opentelemetry-collector-contrib:0.107.0
          args:
            - "--config=/conf/otel-collector.yaml"
          env:
            - name: GOMAXPROCS
              valueFrom:
                resourceFieldRef:
                  containerName: *app
                  resource: limits.cpu
            - name: GOMEMLIMIT
              valueFrom:
                resourceFieldRef:
                  containerName: *app
                  resource: limits.memory
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
            limits:
              # Note: used by GOMAXPROCS in env, which will round up
              # e.g. '1500m' -> '2'
              cpu: 1
              memory: 3Gi
          readinessProbe:
            httpGet:
              path: /
              port: 13133
          livenessProbe:
            httpGet:
              path: /
              port: 13133
          ports:
            - name: otlp
              containerPort: 4317
            - name: ext-zpages
              containerPort: 55679
            - name: collector-prom
              containerPort: 8888
            - name: prom
              containerPort: 8889
          volumeMounts:
            - name: otel-collector-config-vol
              mountPath: /conf
      volumes:
        - name: otel-collector-config-vol
          configMap:
            name: otel-collector
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - *app
