apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-conf
  labels:
    app: otel-collector
data:
  otel-collector-config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      batch:
      memory_limiter:
        check_interval: 5s
        limit_percentage: 80
        spike_limit_percentage: 25
    extensions:
      memory_ballast:
        size_mib: 80
      health_check: {}
      zpages: {}
    exporters:
      jaeger:
        endpoint: "jaeger-collector.otel:14250"
        insecure: true
      logging:
        loglevel: debug
      prometheus:
        endpoint: "0.0.0.0:8889"
        resource_to_telemetry_conversion:
          enabled: true
    service:
      extensions: [health_check, zpages]
      pipelines:
        traces/jaeger:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [logging]
        metrics/prometheus:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [prometheus]
