apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: prometheus
    files:
      - prometheus.yml=config/prometheus.yaml

resources:
  - statefulset.yaml
  - services.yaml
  - disruption-budget.yaml

images:
  - name: prometheus
    newName: prom/prometheus
    newTag: v2.53.2
