apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  ports:
    - name: prometheus
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app: prometheus
---
# Allows remote_write_api to push into each Prometheus instance for redundency
apiVersion: v1
kind: Service
metadata:
  name: prometheus-push
  annotations:
    # Scrapes metrics about Prometheus instance, not the metrics we push in.
    # Those metrics are scraped using federation on the shared infra Thanos instance.
    prometheus.io/path: /metrics
    prometheus.io/port: "9090"
    prometheus.io/scrape: "true"
spec:
  ports:
    - name: prometheus
      port: 9090
      protocol: TCP
      targetPort: 9090
  clusterIP: None
  selector:
    app: prometheus
