apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: &app tempo-metrics-generator
  annotations:
    "app.uw.systems/description": "Tempo metrics-generator processes spans and write metrics to Prometheus"
    "app.uw.systems/tier": "tier_3"
    "app.uw.systems/tags.oss": "true"
    "app.uw.systems/repos.manifests": "https://github.com/utilitywarehouse/opentelemetry-manifests"
    "app.uw.systems/repos.tempo": "https://github.com/grafana/tempo"
spec:
  podManagementPolicy: Parallel
  replicas: 3
  selector:
    matchLabels:
      app: *app
      tempo-gossip-member: "true"
  serviceName: *app
  template:
    metadata:
      labels:
        app: *app
        tempo-gossip-member: "true"
      annotations:
        injector.tumblr.com/request: vault-sidecar-aws
        prometheus.io/scrape: "true"
        prometheus.io/port: "3200"
        prometheus.io/path: /metrics
    spec:
      serviceAccountName: tempo
      terminationGracePeriodSeconds: 90
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: *app
            topologyKey: kubernetes.io/hostname
      initContainers:
        - name: chown-var-tempo
          image: alpine:3.7
          args:
            - chown
            - -R
            - 10001:10001
            - /var/tempo
          volumeMounts:
            - name: datadir
              mountPath: /var/tempo
      containers:
        - name: generator
          image: tempo
          args:
            - -target=metrics-generator
            - -config.file=/conf/tempo.yaml
            - -mem-ballast-size-mbs=1024
            - -config.expand-env=true
          envFrom:
            - configMapRef:
                name: tempo-config-overlay
          resources:
            requests:
              cpu: 200m
              memory: 500Mi
            limits:
              cpu: 1500m
              memory: 2Gi
          readinessProbe:
            httpGet:
              path: /ready
              port: 3200
            initialDelaySeconds: 15
            timeoutSeconds: 1
          ports:
            - name: prom-metrics
              containerPort: 3200
          volumeMounts:
            - name: tempo-config-vol
              mountPath: /conf
            - name: datadir
              mountPath: /var/tempo
      volumes:
        - name: tempo-config-vol
          configMap:
            name: tempo
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
    - metadata:
        name: datadir
        labels:
          app: *app
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
