apiVersion: apps/v1
kind: Deployment
metadata:
  name: &app tempo-distributor
  labels:
    app: *app
  annotations:
    "app.uw.systems/description": "Tempo distributors receive spans and forward them to the appropriate ingesters"
    "app.uw.systems/tier": "tier_3"
    "app.uw.systems/tags.oss": "true"
    "app.uw.systems/repos.manifests": "https://github.com/utilitywarehouse/opentelemetry-manifests"
    "app.uw.systems/repos.tempo": "https://github.com/grafana/tempo"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: *app
      tempo-gossip-member: "true"
  template:
    metadata:
      name: *app
      labels:
        app: *app
        tempo-gossip-member: "true"
      annotations:
        injector.tumblr.com/request: vault-sidecar-aws
        prometheus.io/scrape: "true"
        prometheus.io/port: "3200"
        prometheus.io/path: /metrics
    spec:
      serviceAccountName: tempo
      terminationGracePeriodSeconds: 60
      containers:
        - name: distributor
          image: tempo
          args:
            - -target=distributor
            - -config.file=/conf/tempo.yaml
            - -mem-ballast-size-mbs=1024
            - -config.expand-env=true
            - -shutdown-delay=15s
          envFrom:
            - configMapRef:
                name: tempo-config-overlay
          resources:
            requests:
              cpu: 0
              memory: 1Gi
            limits:
              cpu: 2
              memory: 4Gi
          readinessProbe:
            httpGet:
              path: /ready
              port: 3200
            initialDelaySeconds: 15
            timeoutSeconds: 1
          ports:
            - name: prom-metrics
              containerPort: 3200
          volumeMounts:
            - name: tempo-config-vol
              mountPath: /conf
            - name: tempo-distributor-kafka-client-certificate
              mountPath: /kafka-client-certificate
              readOnly: true
      volumes:
        - name: tempo-config-vol
          configMap:
            name: tempo
        - name: tempo-distributor-kafka-client-certificate
          secret:
            secretName: tempo-distributor-kafka-client-certificate
