apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: tempo
    files:
      - tempo.yaml=config.yaml
  - name: tempo-config-overlay
    # Env from this configmap are injected to Tempo deploys/sts in order to be used in tempo.yaml.
    # Currently, there is no way to template configmap contents using Kustomize.
    literals:
      - S3_BUCKET=example-s3-bucket

resources:
  - auth.yaml
  - discovery.yaml

  - compactor
  - distributor
  - ingester
  - memcached
  - metrics-generator
  - querier
  - query-frontend

images:
  - name: tempo
    newName: grafana/tempo
    newTag: 2.4.0
