apiVersion: apps/v1
kind: Deployment
metadata:
  name: &app tempo-querier
  labels:
    app: *app
  annotations:
    "app.uw.systems/description": "Tempo queriers are responsible for querying the backends/cache for the traceID"
    "app.uw.systems/tier": "tier_3"
    "app.uw.systems/tags.oss": "true"
    "app.uw.systems/repos.manifests": "https://github.com/utilitywarehouse/opentelemetry-manifests"
    "app.uw.systems/repos.tempo": "https://github.com/grafana/tempo"
spec:
  replicas: 10
  selector:
    matchLabels:
      app: *app
      tempo-gossip-member: "true"
  template:
    metadata:
      name: *app
      labels:
        app: *app
        tempo-gossip-member: "true"
      annotations:
        injector.tumblr.com/request: vault-sidecar-aws
        prometheus.io/scrape: "true"
        prometheus.io/port: "3200"
        prometheus.io/path: /metrics
    spec:
      serviceAccountName: tempo
      terminationGracePeriodSeconds: 60
      containers:
        - name: querier
          image: tempo
          args:
            - -target=querier
            - -config.file=/conf/tempo.yaml
            - -config.expand-env=true
            - -shutdown-delay=15s
          env:
            - name: GOMEMLIMIT
              value: "4500MiB"
          envFrom:
            - configMapRef:
                name: tempo-config-overlay
          resources:
            requests:
              cpu: 100m
              memory: 1Gi
            limits:
              cpu: 1
              memory: 5Gi
          readinessProbe:
            httpGet:
              path: /ready
              port: 3200
            initialDelaySeconds: 15
            timeoutSeconds: 1
          ports:
            - name: prom-metrics
              containerPort: 3200
          volumeMounts:
            - name: tempo-config-vol
              mountPath: /conf
      volumes:
        - name: tempo-config-vol
          configMap:
            name: tempo
