apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: &app otel-collector
spec:
  selector:
    matchLabels:
      app: *app
  maxUnavailable: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: &app otel-collector
spec:
  selector:
    matchLabels:
      app: *app
  replicas: 3
  minReadySeconds: 5
  progressDeadlineSeconds: 120
  template:
    metadata:
      name: *app
      labels:
        app: *app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8888"
        prometheus.io/path: /metrics
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: *app
          image: otel/opentelemetry-collector-contrib:0.75.0
          args:
            - "--config=/conf/otel-collector.yaml"
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
            limits:
              cpu: 1
              memory: 3Gi
          readinessProbe:
            httpGet:
              path: /
              port: 13133
          livenessProbe:
            httpGet:
              path: /
              port: 13133
          ports:
            - name: otlp
              containerPort: 4317
            - name: ext-zpages
              containerPort: 55679
            - name: collector-prom
              containerPort: 8888
            - name: prom
              containerPort: 8889
          volumeMounts:
            - name: otel-collector-config-vol
              mountPath: /conf
      volumes:
        - name: otel-collector-config-vol
          configMap:
            name: otel-collector
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - *app
