apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-agent-conf
  labels:
    app: otel-agent
data:
  otel-agent-config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      batch:
      memory_limiter:
        check_interval: 5s
        limit_percentage: 80
        spike_limit_percentage: 25
        # Same as --mem-ballast-size-mib CLI argument
        ballast_size_mib: 60
    extensions:
      health_check: {}
      zpages: {}
    exporters:
      otlp:
        endpoint: "otel-agent-gateway.partner:4317"
        insecure: true
        sending_queue:
          enabled: true
          queue_size: 15000
        retry_on_failure:
          enabled: true
          max_elapsed_time: 1800s
    service:
      extensions: [health_check, zpages]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [otlp]
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [otlp]
        logs:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [otlp]
