---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

# Env from this configmap are injected to Tempo deploys/ sts in order to be used in tempo.yaml.
# Currently, there is no way to template configmap contents using Kustomize.
configMapGenerator:
  - name: tempo-config-overlay
    behavior: replace
    literals:
      - S3_BUCKET=example-s3-bucket
