apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-conf
  labels:
    app: otel-collector
data:
  otel-collector-config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      batch:
      memory_limiter:
        # Same as --mem-ballast-size-mib CLI argument
        ballast_size_mib: 683
        # 80% of maximum memory
        limit_mib: 1500
        # 25% of limi
        spike_limit_mib: 512
        check_interval: 5s
    extensions:
      health_check: {}
      zpages: {}
    exporters:
      jaeger:
        endpoint: "jaeger-collector.partner:14250"
        insecure: true
      logging:
        loglevel: debug
    service:
      extensions: [health_check, zpages]
      pipelines:
        traces/jaeger:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [logging]
